In [ ]:
import numpy as np

coordinates = np.genfromtxt('input.txt',delimiter=',',dtype=int)

def distance(a,b):
    return abs(a[0]-b[0]) + abs(a[1]-b[1])

minX = np.min(coordinates[:,0])
maxX = np.max(coordinates[:,0])
minY = np.min(coordinates[:,1])
maxY = np.max(coordinates[:,1])

grid = -np.ones([maxX - minX + 3, maxY - minY + 3], int)

for index, point in enumerate(coordinates):
    plotpoint = point-[minX,minY]+[1,1]
    grid[plotpoint[0],plotpoint[1]] = index

print(grid)
areas = np.zeros(coordinates.shape[0], int)

for i in range(minX-1, maxX+2):
    for j in range(minY-1, maxY+2):
        distances = [distance(x,[i,j]) for x in coordinates]
        minDistance = min(distances)
        indices = [i for i, x in enumerate(distances) if x == minDistance]
        if len(indices) == 1:
            grid[i - minX + 1, j - minY + 1] = indices[0]
            areas[indices[0]] += 1
print(grid[0,:])

edgecoordinates = np.unique(np.concatenate([np.unique(grid[:,0]),np.unique(grid[:,grid.shape[1]-1]),\
       np.unique(grid[0,:]),np.unique(grid[grid.shape[0]-1,:])]))

noInfiniteAreas = [x for i,x in enumerate(areas) if i not in edgecoordinates]
print(areas)
print(noInfiniteAreas) 
        

[[-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 ...
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]]
