In [56]:
import numpy as np
import re

def addr(A,B,C):
    reg[C] = reg[A] + reg[B]
    
def addi(A,B,C):
    reg[C] = reg[A] + B
    
def mulr(A,B,C):
    reg[C] = reg[A] * reg[B]

def muli(A,B,C):
    reg[C] = reg[A] * B
    
def banr(A,B,C):
    reg[C] = reg[A] & reg[B]
    
def bani(A,B,C):
    reg[C] = reg[A] & B
    
def borr(A,B,C):
    reg[C] = reg[A] | reg[B]
    
def bori(A,B,C):
    reg[C] = reg[A] | B
    
def setr(A,B,C):
    reg[C] = reg[A]
    
def seti(A,B,C):
    reg[C] = A
    
def gtir(A,B,C):
    reg[C] = 1 if A > reg[B] else 0
    
def gtri(A,B,C):
    reg[C] = 1 if reg[A] > B else 0
    
def gtrr(A,B,C):
    reg[C] = 1 if reg[A] > reg[B] else 0
    
def eqir(A,B,C):
    reg[C] = 1 if A == reg[B] else 0
    
def eqri(A,B,C):
    reg[C] = 1 if reg[A] == B else 0
    
def eqrr(A,B,C):
    reg[C] = 1 if reg[A] == reg[B] else 0

def fields_view(array, fields):
    return array.getfield(np.dtype(
        {name: array.dtype.fields[name] for name in fields}
    ))
    
operations = [addr, addi, mulr, muli, banr, bani, borr, bori, setr, seti, gtir,
              gtri, gtrr, eqir, eqri, eqrr]

data = np.genfromtxt('input.txt',comments='#',dtype=[('<U16'),(int),(int),(int)],delimiter=' ')

instructions = fields_view(data,data[0].dtype.names[1:])

#ip 4
ipReg = 4
ip = 0
reg = np.zeros(6, int)
reg[0] = 1
i = 0
while True:
    instruction = instructions[ip]    
    reg[ipReg] = ip
    locals()[data[ip][0]](*instruction)
    ip = reg[ipReg]
    ip += 1
    if ip > data.size:
        break
    
    print(reg)
    i+= 1
    if i == 20:
        break
    
print(reg)
    

[ 1  0  0  0 16  0]
[ 1  0  0  0 17  2]
[ 1  0  0  0 18  4]
[ 1  0  0  0 19 76]
[  1   0   0   0  20 836]
[  1   0   5   0  21 836]
[  1   0 110   0  22 836]
[  1   0 128   0  23 836]
[  1   0 128   0  24 964]
[  1   0 128   0  26 964]
[  1   0  27   0  27 964]
[  1   0 756   0  28 964]
[  1   0 785   0  29 964]
[    1     0 23550     0    30   964]
[     1      0 329700      0     31    964]
[       1        0 10550400        0       32      964]
[       1        0 10550400        0       33 10551364]
[       0        0 10550400        0       34 10551364]
[       0        0 10550400        0        0 10551364]
[       0        0 10550400        1        1 10551364]
[       0        0 10550400        1        1 10551364]


In [55]:
part1 = 964
part2 = 10551364
def func(F):
    A = 0
    for i in range(1,F+1):
        if F % i == 0:
            D = F // i
            A += D
    return A
        
print(func(part1))
print(func(part2))

1694
18964204
