In [43]:
import numpy as np
import re

data = open('test.txt','r').read().splitlines()
# '.' = 0, '|' = 1, '~' = 2, '#' = 3
grid = np.zeros((1850,1850), int)
for line in data:
    num = [int(char) for char in re.findall('\d+', line)]
    if line[0] == 'x':
        grid[num[1]:num[2]+1,num[0]] = 3
    elif line[0] == 'y':
        grid[num[0],num[1]:num[2]+1] = 3
        
ymin, ymax = np.where(grid==3)[0][0], np.where(grid==3)[0][-1]
        
source = (0,500)
grid[source] = -1

def flow(y,x):
    current = (y,x)
    below = (y+1,x)
    left = (y,x-1)
    right = (y,x+1)
    above = (y-1,x)    
    
    while grid[y+1,x] == 0:
        grid[y+1,x] = 1
        y += 1
        if y == grid.shape[0]:
            return
    print(y)
    if grid[below] > 1:
        if grid[left] == 0:
            grid[left] = 1
            flow(*left)
        if grid[right] == 0:
            grid[right] = 1
            flow(*right)
    print(testGrid)
    if grid[above] == 1:
        nextWall = x
        if nextWall>grid.shape[0]:
            print("Error")
        while grid[y,nextWall] != 3:
            nextWall += 1
            if nextWall == grid.shape[0]:
                return
        prevWall = x
        while grid[y,prevWall] != 3:
            prevWall -= 1
            if prevWall < 0:
                return
        if np.array([(grid[y,prevWall+1:nextWall] == np.ones(nextWall-(prevWall+1)))]).all():
            grid[y,prevWall+1:nextWall] = 2
        print(testGrid)
        flow(*above)
        

testGrid = grid[:15,494:508]
flow(*source)


unique, counts = np.unique(grid[ymin:ymax+1,:], return_counts=True)
countGrid = dict(zip(unique, counts))

print(countGrid)
print(countGrid[1]+countGrid[2])
print(testGrid)
        

6
[[ 0  0  0  0  0  0 -1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  0  0  0  3  0]
 [ 0  3  0  0  3  0  1  0  0  0  0  0  3  0]
 [ 0  3  0  0  3  0  1  3  0  0  0  0  0  0]
 [ 0  3  0  0  3  0  1  3  0  0  0  0  0  0]
 [ 0  3  0  0  0  0  1  3  0  0  0  0  0  0]
 [ 0  3  0  0  0  0  1  3  0  0  0  0  0  0]
 [ 0  3  3  3  3  3  3  3  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  3  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  3  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  3  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  3  3  3  3  3  3  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
{0: 24010, 1: 6, 3: 34}


KeyError: 2